---
- name: configure KDE applications
  hosts: localhost
  tasks:
    - name: install kde packages
      become: yes
      yum:
        name:
          - yakuake
          - google-noto-emoji-color-fonts
          - ibus-uniemoji
          - kde-connect
          - vlc
    - name: remove unnecessary KDE applications
      yum:
        name:
          - karbon
          -
      
