---
- name: configure shell environment
  hosts: localhost
  tasks:
    - name: install shell packages
      become: yes
      yum:
        name:
          - zsh
          - git
          - podman
          - tmux
          - vim
          - fira-code-fonts
        state: present

    - name: don't use nano as default editor
      become: yes
      yum:
        name: nano-default-editor
        state: absent

    - name: drop in .vimrc
      copy:
        src: vimrc
        dest: "{{lookup('env', 'HOME')}}/.vimrc"

    - name: install tmux-themepack
      git:
        repo: https://github.com/jimeh/tmux-themepack.git
        dest: "{{lookup('env', 'HOME')}}/.config/tmux-themepack"

    - name: drop in .tmux.conf
      copy:
        src: tmux.conf
        dest: "{{lookup('env', 'HOME')}}/.tmux.conf"

    - name: change shell to /usr/bin/zsh
      become: yes
      user:
        name: "{{lookup('env', 'USER')}}"
        shell: /usr/bin/zsh

