---
- name: workshop configuration
  hosts: localhost
  tasks:
    - name: create workshop
      become: yes
      file:
        path: /var/lib/workshop
        mode: '0750'
        state: directory
        owner: akdev
        group: akdev
